name: GitStats Preview

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the `main` branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-tags: 0 # git all history.

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuplot

    - name: Generate GitStats Report
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install .

        mkdir -p gitstats-report
        gitstats . gitstats-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gitstats-report
        # Configure a unique preview link for each pull request
        destination_dir: previews/${{ github.event.pull_request.number }}

    - name: Add PR Comment with Preview Link
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_NAME: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        PREVIEW_URL="https://shenxianpeng.github.io/gitstats/previews/${{ env.PR_NUMBER }}/index.html"
        COMMENT_BODY="🎉 Your GitStats preview is ready: [View Report](${PREVIEW_URL})"
        gh api repos/${{ env.REPO_NAME }}/issues/${{ env.PR_NUMBER }}/comments -f body="${COMMENT_BODY}"
